### ISSUE TITLE
USB Timeout on OSX

### ISSUE THREAD

**Issue by half2me** [SamyCookie/python-ant#12]
Hi, under linux the demo script for HR monitor works perfectly, but under OSX I get the following error one second after starting.

Listening for HR monitor events (120 seconds)...
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 763, in run
    self.__target(_self.__args, *_self.__kwargs)
  File "build/bdist.macosx-10.11-intel/egg/ant/core/event.py", line 50, in EventPump
    buffer_ += evm.driver.read(20)
  File "build/bdist.macosx-10.11-intel/egg/ant/core/driver.py", line 77, in read
    data = self._read(count)
  File "build/bdist.macosx-10.11-intel/egg/ant/core/driver.py", line 235, in _read
    return self._epIn.read(count).tostring()
  File "build/bdist.macosx-10.11-intel/egg/usb/core.py", line 402, in read
    return self.device.read(self, size_or_buffer, timeout)
  File "build/bdist.macosx-10.11-intel/egg/usb/core.py", line 988, in read
    self.__get_timeout(timeout))
  File "build/bdist.macosx-10.11-intel/egg/usb/backend/libusb1.py", line 833, in bulk_read
    timeout)
  File "build/bdist.macosx-10.11-intel/egg/usb/backend/libusb1.py", line 936, in __read
    _check(retval)
  File "build/bdist.macosx-10.11-intel/egg/usb/backend/libusb1.py", line 595, in _check
    raise USBError(_strerror(ret), ret, _libusb_errno[ret])
USBError: [Errno 60] Operation timed out

**Comment by SamyCookie** [comment]
Could you test by changing this line
https://github.com/SamyCookie/python-ant/blob/dev/src/ant/core/event.py#L52
by
`if e.errno in (60, 110): # timeout` ?

**Comment by half2me** [comment]
works fine :) That fixed it!
